import { Platform, StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f1f6f5' },
  scrollContent: { paddingBottom: 28 },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 18, backgroundColor: '#e4f1ee', borderBottomWidth: 1, borderBottomColor: '#d6e7e3', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', overflow: 'hidden' },
  headerOrbOne: { position: 'absolute', width: 130, height: 130, borderRadius: 65, backgroundColor: 'rgba(255,255,255,0.28)', right: -55, top: -72 },
  headerOrbTwo: { position: 'absolute', width: 74, height: 74, borderRadius: 37, backgroundColor: 'rgba(239,121,94,0.10)', right: 62, bottom: -45 },
  headerCopy: { flex: 1, paddingRight: 14 },
  greeting: { color: '#2f7d70', fontSize: 12, fontWeight: '800', letterSpacing: 1.5, marginBottom: 5 },
  heading: { color: '#17364b', fontSize: 28, lineHeight: 34, fontWeight: '800' },
  locationRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 4 },
  locationText: { color: '#71808a', fontSize: 11 },
  profileButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#e2edf1', alignItems: 'center', justifyContent: 'center' },
  notificationDot: { position: 'absolute', width: 8, height: 8, borderRadius: 4, backgroundColor: '#ef795e', borderWidth: 2, borderColor: '#e2edf1', right: 1, top: 1 },
  searchBox: { height: 52, marginHorizontal: 20, marginTop: 14, marginBottom: 26, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: '#dbe8e5', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, shadowColor: '#274656', shadowOpacity: 0.07, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  searchInput: { flex: 1, color: '#203747', fontSize: 14, marginLeft: 10 },
  offerBanner: { minHeight: 132, marginHorizontal: 20, marginBottom: 28, borderRadius: 20, backgroundColor: '#ffe6d9', borderWidth: 1, borderColor: '#f7cdb9', overflow: 'hidden', flexDirection: 'row', alignItems: 'center', paddingLeft: 18, paddingRight: 20 },
  offerCircleLarge: { position: 'absolute', width: 150, height: 150, borderRadius: 75, backgroundColor: 'rgba(255,255,255,0.25)', right: -42, top: -30 },
  offerCircleSmall: { position: 'absolute', width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(239,121,94,0.14)', right: 75, bottom: -14 },
  offerCopy: { flex: 1 },
  offerEyebrow: { color: '#c65f4d', fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 7 },
  offerTitle: { color: '#17364b', fontSize: 18, lineHeight: 23, fontWeight: '800', maxWidth: 220 },
  offerButton: { alignSelf: 'flex-start', marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 7, paddingVertical: 7, paddingHorizontal: 10, borderRadius: 8, backgroundColor: '#fff' },
  offerButtonText: { color: '#203747', fontSize: 11, fontWeight: '700' },
  offerIcon: { transform: [{ rotate: '-12deg' }] },
  section: { marginBottom: 27 },
  sectionHeader: { paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 },
  sectionTitle: { color: '#17364b', fontSize: 21, fontWeight: '800' },
  sectionAction: { color: '#d96652', fontSize: 13, fontWeight: '800' },
  sectionSubtitle: { color: '#8a989b', fontSize: 11, marginTop: 4 },
  serviceCount: { color: '#71808a', fontSize: 11, fontWeight: '700' },
  ratingPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 6, paddingHorizontal: 9, borderRadius: 10, backgroundColor: '#fff4df' },
  categoryList: { paddingHorizontal: 20, gap: 12 },
  categoryTile: { width: 76, alignItems: 'center' },
  categoryIcon: { width: 64, height: 64, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(32,55,71,0.05)', alignItems: 'center', justifyContent: 'center', marginBottom: 8, shadowColor: '#274656', shadowOpacity: 0.06, shadowRadius: 7, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  categoryIconSelected: { borderWidth: 2, borderColor: '#ef795e' },
  categoryLabel: { color: '#44545d', fontSize: 11, textAlign: 'center' },
  categoryLabelSelected: { color: '#1e3445', fontWeight: '700' },
  serviceList: { paddingHorizontal: 20, gap: 14 },
  serviceCard: { width: 220, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: '#dfeae8', overflow: 'hidden', shadowColor: '#274656', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  serviceImage: { width: '100%', height: 124, backgroundColor: '#e7eeee' },
  serviceContent: { padding: 12 },
  serviceMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 7 },
  servicePrice: { color: '#72838a', fontSize: 12, fontWeight: '600' },
  rating: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  ratingText: { color: '#52636a', fontSize: 11, fontWeight: '700' },
  serviceTitle: { color: '#203747', fontSize: 15, fontWeight: '700', marginBottom: 5 },
  serviceDescription: { color: '#7b878b', fontSize: 11, lineHeight: 15, minHeight: 30, marginBottom: 11 },
  bookButton: { minHeight: 38, borderRadius: 9, backgroundColor: '#e96f58', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 11 },
  bookButtonBooked: { backgroundColor: '#5c9074' },
  bookButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  emptyState: { marginHorizontal: 20, padding: 28, borderRadius: 16, backgroundColor: '#fff', alignItems: 'center' },
  emptyTitle: { color: '#203747', fontSize: 16, fontWeight: '700', marginTop: 10 },
  emptyText: { color: '#7b878b', fontSize: 13, textAlign: 'center', marginTop: 5 },
  trustRow: { marginHorizontal: 20, marginTop: 28, paddingTop: 17, borderTopWidth: 1, borderTopColor: '#e4ece9', flexDirection: 'row', justifyContent: 'space-between' },
  trustItem: { alignItems: 'center', gap: 6, flex: 1 },
  trustText: { color: '#71808a', fontSize: 10, textAlign: 'center' },
  pageContent: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 24, paddingBottom: 34, backgroundColor: '#f1f6f5' },
  pageEyebrow: { color: '#d96652', fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginBottom: 7 },
  pageTitle: { color: '#17364b', fontSize: 30, fontWeight: '800', marginBottom: 24 },
  bookingCard: { borderRadius: 16, backgroundColor: '#fff', padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, shadowColor: '#274656', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  bookingIcon: { width: 46, height: 46, borderRadius: 14, backgroundColor: '#fff0eb', alignItems: 'center', justifyContent: 'center' },
  bookingCopy: { flex: 1 },
  bookingStatus: { color: '#ef795e', fontSize: 9, fontWeight: '800', letterSpacing: 1, marginBottom: 4 },
  bookingTitle: { color: '#203747', fontSize: 15, fontWeight: '700' },
  bookingDetails: { color: '#7b878b', fontSize: 12, lineHeight: 17, marginTop: 5 },
  emptyPage: { alignItems: 'center', paddingVertical: 58, paddingHorizontal: 20, borderRadius: 18, backgroundColor: '#fff' },
  primaryButton: { marginTop: 20, minHeight: 42, paddingHorizontal: 20, borderRadius: 10, backgroundColor: '#ef795e', alignItems: 'center', justifyContent: 'center' },
  primaryButtonText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  messageCard: { flexDirection: 'row', gap: 12, padding: 15, marginBottom: 12, borderRadius: 16, backgroundColor: '#fff' },
  messageIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: '#fff0eb', alignItems: 'center', justifyContent: 'center' },
  messageIconGreen: { backgroundColor: '#e4f0e8' },
  messageCopy: { flex: 1 },
  messageTime: { color: '#a0abad', fontSize: 10, marginTop: 8 },
  profileCard: { padding: 16, borderRadius: 16, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 18 },
  profileAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#e2edf1', alignItems: 'center', justifyContent: 'center' },
  profileIdentity: { flex: 1 },
  profileName: { color: '#203747', fontSize: 16, fontWeight: '700' },
  profileEmail: { color: '#8a989b', fontSize: 12, marginTop: 4 },
  googleButton: { minHeight: 48, borderRadius: 11, borderWidth: 1, borderColor: '#dfe7e6', backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 10 },
  googleButtonDisabled: { backgroundColor: '#f0f3f2', borderColor: '#e5eae9', opacity: 0.75 },
  googleButtonText: { color: '#304955', fontSize: 13, fontWeight: '700' },
  loginError: { color: '#c85f54', fontSize: 12, textAlign: 'center', marginBottom: 10 },
  signOutButton: { minHeight: 44, borderRadius: 11, borderWidth: 1, borderColor: '#f1c8c1', alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  signOutText: { color: '#c85f54', fontSize: 13, fontWeight: '700' },
  authPage: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 34, backgroundColor: '#f1f6f5' },
  authBack: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#e8f0ef', alignItems: 'center', justifyContent: 'center', marginBottom: 28 },
  authBrand: { color: '#ef795e', fontSize: 14, fontWeight: '800', letterSpacing: 1.3, marginBottom: 10 },
  authTitle: { color: '#203747', fontSize: 30, lineHeight: 36, fontWeight: '700' },
  authSubtitle: { color: '#71808a', fontSize: 14, lineHeight: 21, marginTop: 9, marginBottom: 25 },
  roleLabel: { color: '#52656c', fontSize: 12, fontWeight: '700', marginBottom: 9 },
  roleList: { flexDirection: 'row', gap: 7, marginBottom: 20 },
  roleOption: { flex: 1, minHeight: 42, borderRadius: 10, borderWidth: 1, borderColor: '#dfe7e6', backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  roleOptionSelected: { borderColor: '#ef795e', backgroundColor: '#fff1eb' },
  roleOptionText: { color: '#71808a', fontSize: 11, fontWeight: '700' },
  roleOptionTextSelected: { color: '#c85f4d' },
  authTabs: { height: 48, borderRadius: 12, backgroundColor: '#e9efed', flexDirection: 'row', padding: 4, marginBottom: 20 },
  authTab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 9 },
  authTabActive: { backgroundColor: '#fff', shadowColor: '#274656', shadowOpacity: 0.07, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  authTabText: { color: '#71808a', fontSize: 13, fontWeight: '600' },
  authTabTextActive: { color: '#203747', fontWeight: '800' },
  authInputWrap: { minHeight: 52, borderRadius: 12, borderWidth: 1, borderColor: '#dfe7e6', backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, marginBottom: 12 },
  authInput: { flex: 1, color: '#203747', fontSize: 14, marginLeft: 10 },
  authDivider: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 16 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#e0e8e6' },
  dividerText: { color: '#9ca7aa', fontSize: 10, fontWeight: '700' },
  authFootnote: { color: '#a0abad', fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 10 },
  roleBadge: { alignSelf: 'flex-start', color: '#2f7d70', fontSize: 9, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase', marginTop: 6 },
  workerSummary: { padding: 18, borderRadius: 17, backgroundColor: '#e4f1ee', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 },
  workerGreeting: { color: '#2f7d70', fontSize: 11, fontWeight: '800', letterSpacing: 0.8, marginBottom: 6 },
  workerSummaryTitle: { color: '#17364b', maxWidth: 230, fontSize: 16, lineHeight: 21, fontWeight: '800' },
  cardHeading: { color: '#17364b', fontSize: 17, fontWeight: '800', marginBottom: 11 },
  kycCard: { padding: 16, borderRadius: 16, backgroundColor: '#fff', marginBottom: 25 },
  kycStatus: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  kycStatusText: { color: '#52656c', fontSize: 13, fontWeight: '800' },
  kycHelp: { color: '#7b878b', fontSize: 12, lineHeight: 17, marginBottom: 14 },
  formInput: { minHeight: 46, borderWidth: 1, borderColor: '#dfe7e6', borderRadius: 10, paddingHorizontal: 12, color: '#203747', fontSize: 13, marginBottom: 10 },
  uploadButton: { minHeight: 44, borderRadius: 10, borderWidth: 1, borderStyle: 'dashed', borderColor: '#b8c9c6', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginBottom: 13 },
  uploadText: { color: '#466175', fontSize: 12, fontWeight: '700' },
  infoRow: { padding: 15, borderRadius: 14, backgroundColor: '#fff4df', flexDirection: 'row', alignItems: 'center', gap: 10 },
  infoText: { flex: 1, color: '#6d6c5c', fontSize: 12, lineHeight: 17 },
  adminStats: { padding: 16, borderRadius: 16, backgroundColor: '#17364b', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 23 },
  statValue: { color: '#fff', fontSize: 22, fontWeight: '800', textAlign: 'center' },
  statLabel: { color: '#b8d0d3', fontSize: 9, textAlign: 'center', marginTop: 4 },
  verificationCard: { padding: 15, borderRadius: 15, backgroundColor: '#fff', marginBottom: 12 },
  verificationTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  workerAvatar: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#e2edf1', alignItems: 'center', justifyContent: 'center' },
  verificationCopy: { flex: 1 },
  queueStatus: { color: '#b78122', fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  queueApproved: { color: '#5c9074' },
  queueRejected: { color: '#c85f54' },
  verificationActions: { flexDirection: 'row', gap: 8, marginTop: 14 },
  rejectButton: { flex: 1, minHeight: 38, borderRadius: 9, borderWidth: 1, borderColor: '#f1c8c1', alignItems: 'center', justifyContent: 'center' },
  rejectText: { color: '#c85f54', fontSize: 12, fontWeight: '800' },
  approveButton: { flex: 1, minHeight: 38, borderRadius: 9, backgroundColor: '#5c9074', alignItems: 'center', justifyContent: 'center' },
  approveText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  profileRow: { minHeight: 58, borderBottomWidth: 1, borderBottomColor: '#e5ebea', flexDirection: 'row', alignItems: 'center', gap: 13 },
  profileRowText: { flex: 1, color: '#40535d', fontSize: 14 },
  modalLayer: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(25, 45, 55, 0.42)' },
  bookingSheet: { backgroundColor: '#fff', borderTopLeftRadius: 25, borderTopRightRadius: 25, paddingHorizontal: 20, paddingTop: 10, paddingBottom: Platform.OS === 'ios' ? 30 : 20 },
  sheetHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#d8e0df', marginBottom: 18 },
  sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 23 },
  sheetEyebrow: { color: '#ef795e', fontSize: 9, fontWeight: '800', letterSpacing: 1.3, marginBottom: 5 },
  sheetTitle: { color: '#203747', fontSize: 21, fontWeight: '700' },
  sheetLabel: { color: '#52656c', fontSize: 12, fontWeight: '700', marginBottom: 9 },
  slotList: { gap: 8, marginBottom: 20 },
  slot: { minHeight: 43, borderRadius: 10, borderWidth: 1, borderColor: '#e3eae8', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 9 },
  slotSelected: { borderColor: '#ef795e', backgroundColor: '#fff4ef' },
  slotText: { color: '#66777d', fontSize: 13 },
  slotTextSelected: { color: '#203747', fontWeight: '700' },
  addressRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#e6eceb', gap: 10 },
  addressCopy: { flex: 1 },
  addressText: { color: '#203747', fontSize: 13, marginTop: 2 },
  bookingSummary: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 18, marginBottom: 14 },
  summaryLabel: { color: '#7b878b', fontSize: 12 },
  summaryPrice: { color: '#203747', fontSize: 16, fontWeight: '800' },
  confirmButton: { minHeight: 50, borderRadius: 11, backgroundColor: '#ef795e', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16 },
  confirmButtonText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  nav: { minHeight: 74, borderTopWidth: 1, borderTopColor: '#e5ebea', backgroundColor: '#fff', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingHorizontal: 8, paddingTop: 8, paddingBottom: Platform.OS === 'ios' ? 18 : 8 },
  navItem: { alignItems: 'center', gap: 4, minWidth: 64 },
  navLabel: { color: '#98a2a7', fontSize: 11 },
  navLabelActive: { color: '#ef795e', fontWeight: '700' },
});